### ISSUE TITLE
Sumatoria de puntos.

### ISSUE THREAD

**Issue by sebas0303** [MDCIrony/Trivia_Silabuz#1]
Cuando me equivoco en una pregunta, debería de restarme puntos pero en lugar de eso, el programa suma más puntos.

![unknown](https://user-images.githubusercontent.com/69934093/190831926-13ea9f98-e448-4620-b059-c55801ed3ceb.png)

**Comment by MDCIrony** [comment]
close with [2bbb921](https://github.com/MDCIrony/Trivia_Silabuz/commit/2bbb921a20b57c2ee23af8433093d1a5b4e515dd)

**Comment by MDCIrony** [comment]
closes with [07da425](https://github.com/MDCIrony/Trivia_Silabuz/commit/07da425750615f2c7be209f0a73fe9e930761169)
